language: ruby
rvm: 2.1.1
env:
  DB=postgresql
deploy:
  provider: heroku
  api_key:
    secure: G73yTkQaMSxANbvwCxr8WVxdHuyiJm073hHDvBdX8oriz70Xhs4Z0nEnXhtq0SHWeHTuiZhVFUTcMfatCxVs3kzeIBla62x1OddbcwVJWkargzsUz+dU9F9WB/ny572oqRdwbk4OIIQkUlpXyRnhXoQwBwfZ72OZwjO4o9c7j8E=
  app: 
    master: epsilon-stage
    production: epsilon-live
  on:
    repo: blazeqwest/epsilon
    branch: dev
  run: "rake db:migrate"
before_script:
  - psql -c 'create database eps_test;' -U postgres
