development:
  adapter: postgresql
  host: localhost
  username: postgres
  password: qwestqwest
  database: eps_dev

test:
  adapter: postgresql
  encoding: utf8
  database: eps_test
  pool: 5
  username: postgres
  password: qwestqwest

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
#  username: 
#  password:
